language: node_js
cache:
  directories:
    - '$HOME/.npm'
notifications:
  email: false
node_js:
  - 'node'
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
after_success:
  - npx codecov
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release